# Use an official Node.js runtime as a parent image
FROM cypress/included:12.17.2

# Set the working directory
WORKDIR /cypress-project

# Copy package.json and package-lock.json (if available)
COPY cypress/ cypress/
COPY cypress/cypress.config.js .
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Verify Cypress installation
RUN npx cypress verify

# Default command
CMD ["cypress", "run", "--spec", "cypress/integration/google.spec.js"]
